### ISSUE TITLE
授权服务器回调时候弹出登录页

### ISSUE THREAD

**Issue by zhuqingze** [hellxz/spring-security-oauth2-learn#1]
授权码模式下 client的回调地址用放行吗？我使用客户端回调时候又弹出了登录页面

**Comment by hellxz** [comment]
> 
> 
> 授权码模式下 client的回调地址用放行吗？我使用客户端回调时候又弹出了登录页面

用的

**Comment by hellxz** [comment]
![](https://user-images.githubusercontent.com/22413769/121289263-3e34a380-c917-11eb-92ad-28ded47bcd13.png)
已更新到代码中。
